[package]
name = "operator-agent"
edition.workspace = true
license.workspace = true
version.workspace = true
autobins = false

[dependencies]
operator-core = { path = "../operator-core" }
operator-runtime = { path = "../operator-runtime" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
operator-testkit = { path = "../operator-testkit" }
