[package]
name = "operator-runtime"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
operator-core = { path = "../operator-core" }
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
operator-testkit = { path = "../operator-testkit" }
tempfile.workspace = true

[dependencies.tokio]
workspace = true
features = ["io-util"]
