[package]
name = "operator-bootstrap"
edition.workspace = true
license.workspace = true
version.workspace = true

[features]
default = []
macos-action-effects = ["operator-platform-macos/action-effects"]

[dependencies]
operator-core = { path = "../operator-core" }
operator-platform-harmony = { path = "../operator-platform-harmony" }
operator-platform-macos = { path = "../operator-platform-macos" }
operator-runtime = { path = "../operator-runtime" }
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
toml_edit.workspace = true

[dev-dependencies]
tempfile.workspace = true
