[package]
name = "operator-platform-harmony"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
hmdriver_rs = { path = "hdc_driver/base" }
image = { version = "0.25.6", default-features = false, features = ["jpeg"] }
operator-core = { path = "../operator-core" }
operator-runtime = { path = "../operator-runtime" }
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dependencies.serde_json]
workspace = true
