[package]
name = "operator-platform-harmony"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
hmdriver_rs = { path = "hdc_driver/base" }
operator-core = { path = "../operator-core" }
operator-runtime = { path = "../operator-runtime" }
thiserror.workspace = true

[dependencies.serde_json]
workspace = true
